const compliments = [
  "you light up every room you enter.",
  "you have the best smile!",
  "your positivity is infectious.",
  "you’re incredibly kind and thoughtful.",
  "you make everything better just by being around.",
  "you’re a ray of sunshine on a cloudy day.",
  "your creativity knows no bounds.",
  "you’re a wonderful friend.",
  "your sense of humor is amazing.",
  "you make people feel seen and valued.",
  "your style is always on point!",
  "you bring out the best in others.",
  "your kindness is a gift to everyone you meet.",
  "you’re genuinely a joy to be around.",
  "you’re the definition of cool.",
  "you inspire everyone to be their best selves.",
  "your laughter is contagious.",
  "you always know the right thing to say.",
  "you have an amazing heart.",
  "your intelligence is off the charts.",
  "you’re a true original.",
  "you have such a calming presence.",
  "you have an eye for detail.",
  "you’re so easy to talk to.",
  "your confidence is admirable.",
  "you’re like a human Wi-Fi—people just connect with you!",
  "you’d be in jail.",
  "you’re as cool as the other side of the pillow.",
  "you could survive a zombie apocalypse with just your charm.",
  "you’re the human equivalent of a pop song stuck in my head.",
  "you’d be a cute-cumber.",
  "you must be made of copper and tellurium because you’re Cu-Te!",
  "you’re so cool that even ice gets jealous.",
  "you’re the reason I came online today.",
  "you’re the life hack everyone needs.",
  "you’re more reliable than auto-save.",
  "you’re the plot twist everyone loves.",
  "you could win an award for just being yourself.",
  "you’ve got more charm than a snake-oil salesman.",
  "you’re as rare as a flawless victory in Super Smash Bros.",
  "you’re like a cloud—always lifting people up!",
  "but not too much to be unbearable.",
  "everyone else disappears!",
  "you’d take gold every time.",
  "you have a natural talent for making everything around you more interesting.",
  "you’re like a walking TED Talk—full of knowledge and inspiration!",
  "you’d be serving a life sentence.",
  "you’re like a human cheat code—everything gets better when you’re around.",
  "you have a way of making everything better just by being yourself.",
  "your presence has a way of brightening up even the dullest day.",
];

module.exports = compliments;
